### ISSUE TITLE
Ore Dictionary support?

### ISSUE THREAD

**Issue by katubug** [asiekierka/UnlimitedChiselWorks#48] opened 2019-06-22 14:06 UTC
Hello! Firstly, thank you for the great mod! :D 

Would it be possible to add ore dictionary support? It seems none of the blocks have any oredict tags. Thank you!

Version: UnlimitedChiselWorks-0.2.1
Minecraft version: 1.12.2

**Comment by asiekierka** [comment] 2019-12-19 20:27
Duplicate of #20, should be fixed by 0.3.3.

**Closed by asiekierka** 2019-12-19 20:27 UTC
Labels: duplicate
